from linked_list import LinkedList

linked_list_test = LinkedList()

linked_list_test.insert(1)
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.insert(2)
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.insert(3)
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.insert(4)
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.insert(5)
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.delete()
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)
linked_list_test.delete()
print("Head: ", linked_list_test.head.node_data)
print("Tail: ", linked_list_test.tail.node_data)

# print("\n", linked_list_test.tail.next.node_data)
linked_list_test.circulify()
print(linked_list_test.tail.next.node_data)

linked_list_test.move_next()
linked_list_test.move_next()
print(linked_list_test.current_node.node_data)
linked_list_test.move_next()
print(linked_list_test.current_node.node_data)
linked_list_test.move_prev()
linked_list_test.move_prev()
print(linked_list_test.current_node.node_data)
linked_list_test.move_prev()
print(linked_list_test.current_node.node_data)